// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDva4CYpk8bSxnyOfP8BVhK5CqmLE02bPo',
    appId: '1:162798110556:web:4ee986ad5e45c2c8232399',
    messagingSenderId: '162798110556',
    projectId: 'to-do-list-1621f',
    authDomain: 'to-do-list-1621f.firebaseapp.com',
    storageBucket: 'to-do-list-1621f.firebasestorage.app',
    measurementId: 'G-YRJ9ZNZTM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFpUyxk8BclQBNA2XH_JXEs3tOqu_saOQ',
    appId: '1:162798110556:android:fdffa788224bd25d232399',
    messagingSenderId: '162798110556',
    projectId: 'to-do-list-1621f',
    storageBucket: 'to-do-list-1621f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtQ6-RNenLYHC6zt6DWWMibNywb0lS9Wo',
    appId: '1:162798110556:ios:e9fb427c7a93ecf3232399',
    messagingSenderId: '162798110556',
    projectId: 'to-do-list-1621f',
    storageBucket: 'to-do-list-1621f.firebasestorage.app',
    iosBundleId: 'com.example.todolistFirebase',
  );
}
